version: 2
jobs:
  build:
    machine: true
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout
      - run: docker run --name some-postgres -e POSTGRES_PASSWORD= -d postgres:9.6.4
      - run: docker pull mlennon3/circdock-ci
      - run: docker run --link some-postgres:postgres-host -it --entrypoint /bin/bash -it -v $(pwd):/home --rm mlennon3/circdock-ci


      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
